export const currentSkills = [
  "Semantic & accessible HTML",
  "Responsive Web Design",
  "Teamwork",
  "Markdown",
  "Immutability",
  "CSS BEM",
  "CSS Grid",
  "CSS Flexbox",
  "React Router",
  "Redux-Saga",
  "Redux Toolkit",
  "React Hooks",
  "Error handling",
  "Working with API (fetch, axios)",
  "JavaScrip: ES6+",
  "Promises, Async/Await",
  "GitHub Pull Requests & Review",
  "Trello",
  "Scrum",
  "NPM",
  "React",
  "Git",
];

export const futureSkills = [
  "TypeScript",
  "JS classes",
  "Cypress",
  "Node.js",
  "React Context",
  "Unit testing",
];
